header-y += tavarua.h
header-y += radio-iris-commands.h

header-y += msm_camera.h
header-y += vcap_fmt.h
header-y += msm_isp.h
header-y += msm_gemini.h
header-y += msm_gestures.h
header-y += msm_mercury.h
header-y += msm_jpeg.h
header-y += msm_media_info.h
header-y += msm_vidc.h
ifeq ($(CONFIG_MSMB_CAMERA_LEGACY),y)
header-y += msmb_camera_v1.h
header-y += msm_cam_sensor_v1.h
header-y += msmb_isp_v1.h
header-y += msmb_ispif_v1.h
header-y += msmb_generic_buf_mgr_v1.h
header-y += msmb_pproc_v1.h
else
header-y += msmb_camera.h
header-y += msm_cam_sensor.h
header-y += msmb_isp.h
header-y += msmb_ispif.h
header-y += msmb_generic_buf_mgr.h
header-y += msmb_pproc.h
endif
